
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: nail1974FI
      MYSQL_DATABASE: bank_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: spring_app_project
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bank_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: nail1974FI
      APP_JWT_SECRET: bankProjectSecretKey_2026_super_long_stringer
      APP_JWT_EXPIRATION_MS: 86400000
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend


volumes:
  mysql_data: